// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getAccMzMatches
List getAccMzMatches(NumericVector& refmz, NumericVector& expmz, NumericVector& ppmThrs);
RcppExport SEXP _misa_getAccMzMatches(SEXP refmzSEXP, SEXP expmzSEXP, SEXP ppmThrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type refmz(refmzSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type expmz(expmzSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type ppmThrs(ppmThrsSEXP);
    rcpp_result_gen = Rcpp::wrap(getAccMzMatches(refmz, expmz, ppmThrs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_misa_getAccMzMatches", (DL_FUNC) &_misa_getAccMzMatches, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_misa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
